#!/bin/env bash

set -euo pipefail

# small wrapper script to create a target directory at a specified location and symlink it as target to project dir
# this is to enable moving the cached build artifacts to a different location.
#
# The primary use case for this script is to move junk data to a location where it will not pollute backups

RUST_CONTAINER=docker.io/rust
RUST_CONTAINER_TAG=${RUST_VERSION:-"latest"}
CARGO_CACHE_BASE_DIR=/var/cache/build-cache/rust

declare -a PODMAN_ARGS=(
	"--rm" "-i" "--log-driver=none"
	"--pull=newer"
	"-v" "$PWD:$PWD:O"
	"-w" "$PWD"
)

# mount local crates registy
if [ -n "${CARGO_HOME:-}" ]; then
	PODMAN_ARGS+=(
		"-v" "$CARGO_HOME/registry:/usr/local/cargo/registry"
	)
else
	PODMAN_ARGS+=(
		"-v" "$HOME/.cargo/registry:/usr/local/cargo/registry"
	)
fi

[[ -t 1 ]] && PODMAN_ARGS+=("-t")

# remove symlinked target directory if exists
# see the following issue for reference https://github.com/containers/podman/issues/25947
[[ -L "$PWD/target" ]] && rm "$PWD/target"

# determine target directory position
if [ -f "Cargo.toml" ] && [ -d "$CARGO_CACHE_BASE_DIR" ] && [ ! -d "$PWD/target" ]; then
	PROJECT_CACHE_DIR="$CARGO_CACHE_BASE_DIR/$(tomlq -r '.package.name' <Cargo.toml)-target"
	[[ ! -f "$PROJECT_CACHE_DIR" ]] && mkdir -p "$PROJECT_CACHE_DIR"
	PODMAN_ARGS+=("-v" "$PROJECT_CACHE_DIR:$PWD/target:rw")
fi

podman run "${PODMAN_ARGS[@]}" --entrypoint cargo "$RUST_CONTAINER:$RUST_CONTAINER_TAG" "$@"

# if mounted project dir was used remove empty target directory and symlink to the project cache directory
[[ -n "${PROJECT_CACHE_DIR:-}" ]] && ln -s "$PROJECT_CACHE_DIR" "$PWD/target"
